# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: dbrecord

---
# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
  clusterIP: None  # headless if needed, optional
---

# Employee Review App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-review
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employeereview-app
  template:
    metadata:
      labels:
        app: employeereview-app
    spec:
      containers:
        - name: employeereview-app
          image: swapnilcareercode/employeereview-app:v1
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/dbrecord
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root

---
# Employee Review App Service
apiVersion: v1
kind: Service
metadata:
  name: employeereview-app-service
spec:
  selector:
    app: employeereview-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
